# Generated by Django 4.2.4 on 2023-08-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="invite_code",
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
